import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // General
          'dashboard': 'Dashboard',
          'tambah': 'Add',
          'edit': 'Edit',
          'hapus': 'Delete',
          'simpan': 'Save',
          'batal': 'Cancel',
          'nama': 'Name',
          'jumlah': 'Amount',
          'tanggal': 'Date',
          'jatuh_tempo': 'Due Date',
          'status': 'Status',
          'belum_lunas': 'Not Paid',
          'lunas': 'Paid',
          'keterangan': 'Note',
          'export_pdf': 'Export PDF',
          'belum_ada_data': 'No data yet',
          'kamera': 'Camera',
          'galeri': 'Gallery',

          // SettingsScreen
          'pengaturan': 'Settings',
          'mata_uang': 'Currency',
          'bahasa': 'Language',
          'manajemen_database': 'Database Management',
          'backup': 'Backup',
          'restore': 'Restore',
          'reset': 'Reset',
          'konfirmasi_reset': 'Reset Confirmation',
          'ketik_reset_untuk_hapus': "Type 'reset' to delete all data",
          'ok': 'OK',
          'backup_berhasil': '✅ Backup successful',
          'restore_berhasil': '✅ Restore database successful',
          'reset_berhasil': '✅ Database successfully reset',
          'gagal_backup': '❌ Backup failed',
          'gagal_restore': '❌ Restore failed',
          'gagal_reset': '❌ Reset failed',
          'lokasi': 'Location',

          // HutangPiutangScreen
          'hutang': 'Debt',
          'piutang': 'Receivable',
          'laporan_hutang_piutang': 'Debt & Receivable Report',
          'tambah_hutang_piutang': 'Add Debt/Receivable',
          'toko_supplier': 'Store → Supplier',
          'pelanggan_toko': 'Customer → Store',
          'laporan_hutang_piutang_seluruh': 'All Debt & Receivable Report',

          // ProdukScreen
          'manajemen_produk': 'Product Management',
          'tambah_produk': 'Add Product',
          'edit_produk': 'Edit Product',
          'nama_produk': 'Product Name',
          'harga': 'Price',
          'stok': 'Stock',
          'deskripsi': 'Description',
          'belum_ada_gambar': 'No image yet',
          'daftar_produk': 'Product List',
          'laporan_daftar_produk': 'Product List Report',
          'penjualan': 'Sales',

          // PenjualanScreen
          'penjualan_harian': 'Daily Sales Report',
          'penjualan_bulanan': 'Monthly Sales Report',
          'pilih_produk': 'Select Product',
          'produk_tidak_ditemukan': 'Product not found',
          'jumlah_harus_lebih_dari_0': 'Amount must be greater than 0',
          'stok_tidak_mencukupi': 'Insufficient stock',
          'produk_jumlah_wajib_diisi': 'Product and amount must be filled',
          'belum_ada_penjualan': 'No sales yet',

          // LaporanPenjualanPdfScreen
          'laporan_penjualan': 'Sales Report',
          'filter_harian': 'Daily',
          'filter_bulanan': 'Monthly',
          'filter_tahunan': 'Yearly',
          'filter_custom': 'Custom Range',
          'tidak_ada_data_penjualan': 'No sales data',
          'total_penjualan': 'Total Sales',

          // InfoTokoScreen
          'info_toko': 'Store Info',
          'nama_toko': 'Store Name',
          'alamat': 'Address',
          'telepon': 'Phone',
          'email': 'Email',
          'nama_toko_wajib_diisi': 'Store name is required',
          'format_email_tidak_valid': 'Invalid email format',
          'info_toko_berhasil_disimpan': 'Store info saved successfully',

          // AboutScreen
          'tentang_aplikasi': 'About App',
          'versi_aplikasi': 'CatatBisnis v1.0',
          'dibuat_oleh': 'Created by: Techtrilabs (developer)',
          'terima_kasih': '🙏 Thank You',
          'donasi_desc': 'If this app is useful and helps you, you can make a voluntary donation (optional) to support further development. Thank you for your support! 💙',
          'donasi_sukarela': 'Voluntary Donation',
          'bank': 'Bank',
          'kode_bank': 'Bank Code',
          'no_rekening': 'Account Number',
          'atas_nama': 'Account Holder',
          'salin_no_rekening': 'Copy Account Number',
          'rekening_disalin': 'Account number copied to clipboard!',
          // DashboardScreen
        
        'total_produk': 'Total Products',
        'stok_habis': 'Out of Stock',
        'penjualan_hari_ini': 'Sales Today',
        'produk': 'Products',   
        'laporan': 'Reports',
        'hutang_piutang': 'Debt & Receivable',        
        'tentang': 'About',

        },
        'id_ID': {
          // General
          'dashboard': 'Dashboard',
          'tambah': 'Tambah',
          'edit': 'Edit',
          'hapus': 'Hapus',
          'simpan': 'Simpan',
          'batal': 'Batal',
          'nama': 'Nama',
          'jumlah': 'Jumlah',
          'tanggal': 'Tanggal',
          'jatuh_tempo': 'Jatuh Tempo',
          'status': 'Status',
          'belum_lunas': 'Belum Lunas',
          'lunas': 'Lunas',
          'keterangan': 'Keterangan',
          'export_pdf': 'Export PDF',
          'belum_ada_data': 'Belum ada data',
          'kamera': 'Kamera',
          'galeri': 'Galeri',

          // SettingsScreen
          'pengaturan': 'Pengaturan',
          'mata_uang': 'Mata Uang',
          'bahasa': 'Bahasa',
          'manajemen_database': 'Manajemen Database',
          'backup': 'Backup',
          'restore': 'Restore',
          'reset': 'Reset',
          'konfirmasi_reset': 'Konfirmasi Reset',
          'ketik_reset_untuk_hapus': "Ketik 'reset' untuk menghapus semua data",
          'ok': 'OK',
          'backup_berhasil': '✅ Backup berhasil',
          'restore_berhasil': '✅ Restore database berhasil',
          'reset_berhasil': '✅ Database berhasil direset',
          'gagal_backup': '❌ Gagal backup',
          'gagal_restore': '❌ Gagal restore',
          'gagal_reset': '❌ Gagal reset',
          'lokasi': 'Lokasi',

          // HutangPiutangScreen
          'hutang': 'Hutang',
          'piutang': 'Piutang',
          'laporan_hutang_piutang': 'Laporan Hutang & Piutang',
          'tambah_hutang_piutang': 'Tambah Hutang/Piutang',
          'toko_supplier': 'Toko → Supplier',
          'pelanggan_toko': 'Pelanggan → Toko',
          'laporan_hutang_piutang_seluruh': 'Laporan Seluruh Hutang & Piutang',

          // ProdukScreen
          'manajemen_produk': 'Manajemen Produk',
          'tambah_produk': 'Tambah Produk',
          'edit_produk': 'Edit Produk',
          'nama_produk': 'Nama Produk',
          'harga_produk': 'Harga',
          'stok': 'Stok',
          'deskripsi': 'Deskripsi',
          'belum_ada_gambar': 'Belum ada gambar',
          'daftar_produk': 'Daftar Produk',
          'laporan_daftar_produk': 'Laporan Daftar Produk',
          'penjualan': 'Penjualan',

          // PenjualanScreen
          'penjualan_harian': 'Laporan Penjualan Harian',
          'penjualan_bulanan': 'Laporan Penjualan Bulanan',
          'pilih_produk': 'Pilih Produk',
          'produk_tidak_ditemukan': 'Produk tidak ditemukan',
          'jumlah_harus_lebih_dari_0': 'Jumlah harus lebih dari 0',
          'stok_tidak_mencukupi': 'Stok produk tidak mencukupi',
          'produk_jumlah_wajib_diisi': 'Produk dan jumlah wajib diisi',
          'belum_ada_penjualan': 'Belum ada penjualan',

          // LaporanPenjualanPdfScreen
          'laporan_penjualan': 'Laporan Penjualan',
          'filter_harian': 'Harian',
          'filter_bulanan': 'Bulanan',
          'filter_tahunan': 'Tahunan',
          'filter_custom': 'Custom Range',
          'tidak_ada_data_penjualan': 'Tidak ada data penjualan',
          'total_penjualan': 'Total Penjualan',

          // InfoTokoScreen
          'info_toko': 'Info Toko',
          'nama_toko': 'Nama Toko',
          'alamat': 'Alamat',
          'telepon': 'Telepon',
          'email': 'Email',
          'nama_toko_wajib_diisi': 'Nama toko wajib diisi',
          'format_email_tidak_valid': 'Format email tidak valid',
          'info_toko_berhasil_disimpan': 'Info Toko berhasil disimpan',

          // AboutScreen
          'tentang_aplikasi': 'Tentang Aplikasi',
          'versi_aplikasi': 'CatatBisnis v1.0',
          'dibuat_oleh': 'Dibuat oleh: Techtrilabs (developer)',
          'terima_kasih': '🙏 Terima Kasih',
          'donasi_desc': 'Jika aplikasi ini bermanfaat dan sangat membantu Anda, Anda dapat memberikan donasi sukarela (tidak wajib) untuk mendukung pengembangan lebih lanjut. Terima kasih atas dukungan Anda! 💙',
          'donasi_sukarela': 'Donasi Sukarela',
          'bank': 'Bank',
          'kode_bank': 'Kode Bank',
          'no_rekening': 'No Rekening',
          'atas_nama': 'Atas Nama',
          'salin_no_rekening': 'Salin Nomor Rekening',
          'rekening_disalin': 'Nomor rekening disalin ke clipboard!',

          // DashboardScreen
          'total_produk': 'Total Produk',
          'stok_habis': 'Stok Habis',
          'penjualan_hari_ini': 'Penjualan Hari Ini',
          'produk': 'Produk',          
          'laporan': 'Laporan',
          'hutang_piutang': 'Hutang Piutang',          
          'tentang': 'Tentang',

        },
      };
}
